POST http://localhost:8080/api/tasks
Content-Type: application/json
Authorization: Bearer TU_TOKEN_JWT_AQUI

{
  "title": "Implementar control de versiones",
  "description": "Hace falta seguimiento",
  "dueDate": "2025-08-20",
  "completed": false
}